apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-2-kustomize
  namespace: flux-system 
spec:
  interval: 10s 
  path: ./manifestes 
  prune: true 
  sourceRef:
    kind: GitRepository
    name: demo-2-kustomize
  targetNamespace: my-app-namespace 
  timeout: 5m0s 
  wait: true 